### ISSUE TITLE
HTML odkazy v textoch nefunguju

### ISSUE THREAD

**Issue by tappdesign** [tappdesign/Knizka#8]
(novena 9 dni)

**Comment by tappdesign** [comment]
anchors doesn't work if Webview is in scroll view

**Comment by pkt2021** [comment]
mas tam kotviace značky bez obsahu 
`<a id="example"></a>`
Vložením niečoho do vnútra sa problém možno vyrieši
`<a id="example">&nbsp;</a>`
ak nepomože skus id vložiť do znacky div
`<div id="Para5" class="PRChoosedTitle">Piaty deň</div>`

**Comment by tappdesign** [comment]
moznosti moze byt viac... Da sa to relativne jednoducho zistit priamo v aplikacii editovanim textu. Ale myslim ze to sposobuje ScrollView. .....a zmena layoutu by bola dost zlozita.

**Comment by tappdesign** [comment]
Sposobuje to scrollView, Anochory nahradene accorditionmi. Ak budu v buducnosti potrebne anchory a scrolovanie, bude nutna zmena layoutu
